#!/usr/bin/env python3
"""
eco_cell_truth_tables.py — Engine for verifying that a chosen cell's boolean
function matches the claimed gate_function.

This module is library-agnostic. It contains:
  - Universal abstract gate-function definitions (AND2, NOR3, AOI21, ... — these
    are mathematical concepts, not tied to any process)
  - Lookup machinery (family_of, truth_table_of, cell_function_matches)

Library-specific data (cell-name → boolean expression) lives in JSON files
under script/eco_scripts/cell_libraries/<library_name>.json. The engine
auto-loads any JSON it finds in that directory and merges them.

Adding support for a new library:
  1. Create script/eco_scripts/cell_libraries/<your_lib>.json
  2. JSON shape: {"<CELL_FAMILY>": {"<output_pin>": "<boolean expression>", ...}}
     Family is the cell-name prefix before drive strength (e.g. AN2D1BWP... → AN2).
     Boolean expression uses Python operators ~, &, |, ^ over input pin names.
  3. Re-run the validator — new entries are picked up automatically.

Adding a single cell to an existing library:
  Edit the relevant JSON. No code changes needed.
"""
import json, os, re

# ── Engine: universal abstract gate-function definitions ─────────────────────
# These are mathematical truth tables for the standard logic functions used
# in study JSON `gate_function` fields. NOT library-specific.

ABSTRACT_GATE_FUNCTIONS = {
    "INV":   {"ZN": "~I"},
    "BUF":   {"Z":  "I"},
    "AND2":  {"Z":  "A1 & A2"},
    "AND3":  {"Z":  "A1 & A2 & A3"},
    "AND4":  {"Z":  "A1 & A2 & A3 & A4"},
    "NAND2": {"ZN": "~(A1 & A2)"},
    "NAND3": {"ZN": "~(A1 & A2 & A3)"},
    "NAND4": {"ZN": "~(A1 & A2 & A3 & A4)"},
    "OR2":   {"Z":  "A1 | A2"},
    "OR3":   {"Z":  "A1 | A2 | A3"},
    "OR4":   {"Z":  "A1 | A2 | A3 | A4"},
    "NOR2":  {"ZN": "~(A1 | A2)"},
    "NOR3":  {"ZN": "~(A1 | A2 | A3)"},
    "NOR4":  {"ZN": "~(A1 | A2 | A3 | A4)"},
    "XOR2":  {"Z":  "A1 ^ A2"},
    "XNOR2": {"ZN": "~(A1 ^ A2)"},
    "INR2":  {"ZN": "A1 & ~B1"},
    "INR3":  {"ZN": "A1 & ~B1 & ~B2"},
    "IINR3": {"ZN": "A1 & A2 & ~B1"},
    "IND2":  {"ZN": "~(~A1 & B1)"},
    "IND3":  {"ZN": "~(A1 & (B1 | B2))"},
    "AOI21": {"ZN": "~((A1 & A2) | B)"},
    "AOI22": {"ZN": "~((A1 & A2) | (B1 & B2))"},
    "OAI21": {"ZN": "~((A1 | A2) & B)"},
    "OAI22": {"ZN": "~((A1 | A2) & (B1 | B2))"},
    "AO21":  {"Z":  "(A1 & A2) | B"},
    "AO22":  {"Z":  "(A1 & A2) | (B1 & B2)"},
    "OA21":  {"Z":  "(A1 | A2) & B"},
    "OA22":  {"Z":  "(A1 | A2) & (B1 | B2)"},
    "AOI211": {"ZN": "~((A1 & A2) | B | C)"},
    "INR4":   {"ZN": "A1 & ~B1 & ~B2 & ~B3"},
    "MUX2":   {"Z":  "S ? I1 : I0"},
}

# ── Engine: regex to extract cell family from a full cell-type string ────────
# Family = cell-name prefix before drive strength suffix.
# Example: AN2D1BWP136P5M156H3P48CPDLVT → AN2
# The drive-strength `D\d+` is REQUIRED in the pattern to stop greedy [A-Z]+ from
# consuming letters AFTER the family (e.g. `INV` in INVD1BWP, not `INVD`).
_FAMILY_RE = re.compile(r"^([A-Z]+\d*)D\d+[A-Z0-9]*$")

def family_of(cell_type):
    """Extract the cell family prefix from a full cell_type string. Returns
    None if the format is unrecognized."""
    if not cell_type:
        return None
    m = _FAMILY_RE.match(cell_type)
    return m.group(1) if m else None

# ── Engine: load library cell data from JSON files ───────────────────────────
_LIBRARY_DATA = None
_REF_DIR_USED = None   # tracks which ref_dir the cache was loaded from

def _load_libraries(ref_dir=None):
    """Load cell truth tables. Priority:
    1. <ref_dir>/data/eco_cell_library.json  — Liberty-extracted per-tile cache
       (auto-generated by eco_liberty_extractor.py; most accurate)
    2. script/eco_scripts/cell_libraries/*.json  — bundled fallback JSON files
       (hand-curated starter set; may have approximate I-prefix entries)

    Call with ref_dir= to pick up the tile-specific cache. Without ref_dir,
    only the bundled fallback is loaded. Cached in-process after first call
    (or when ref_dir changes).
    """
    global _LIBRARY_DATA, _REF_DIR_USED
    if _LIBRARY_DATA is not None and _REF_DIR_USED == ref_dir:
        return _LIBRARY_DATA

    _LIBRARY_DATA = {}
    _REF_DIR_USED = ref_dir

    # 1 — tile-specific Liberty cache (highest priority)
    if ref_dir:
        tile_cache = os.path.join(ref_dir, 'data', 'eco_cell_library.json')
        if os.path.exists(tile_cache):
            try:
                with open(tile_cache) as f:
                    data = json.load(f)
                for family, tt in data.items():
                    if not family.startswith("_"):
                        _LIBRARY_DATA[family] = tt
                # tile cache loaded — bundled fallback still fills any gaps below
            except (json.JSONDecodeError, OSError) as e:
                print(f"WARN: failed to load tile Liberty cache {tile_cache}: {e}")

    # 2 — bundled fallback (fills families not in tile cache)
    lib_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cell_libraries")
    if os.path.isdir(lib_dir):
        for fname in sorted(os.listdir(lib_dir)):
            if not fname.endswith(".json"):
                continue
            path = os.path.join(lib_dir, fname)
            try:
                with open(path) as f:
                    data = json.load(f)
                for family, tt in data.items():
                    if family.startswith("_"):
                        continue
                    if family not in _LIBRARY_DATA:  # tile cache wins on conflict
                        _LIBRARY_DATA[family] = tt
            except (json.JSONDecodeError, OSError) as e:
                print(f"WARN: failed to load cell library {fname}: {e}")

    return _LIBRARY_DATA

def truth_table_of(cell_type_or_function, ref_dir=None):
    """Look up truth table for a full cell name OR an abstract gate_function.
    Pass ref_dir= to pick up the tile-specific Liberty-extracted cache first.
    Returns dict {pin: expr} or None if unknown."""
    if not cell_type_or_function:
        return None
    # Try as abstract gate function first
    if cell_type_or_function in ABSTRACT_GATE_FUNCTIONS:
        return ABSTRACT_GATE_FUNCTIONS[cell_type_or_function]
    # Try as full cell name → extract family → look up library data
    fam = family_of(cell_type_or_function)
    if fam is None:
        return None
    libs = _load_libraries(ref_dir)
    return libs.get(fam)

def cell_function_matches(cell_type, gate_function, ref_dir=None):
    """Compare a chosen cell's truth table to the claimed abstract function.
    Returns (match, reason):
       True  = both known and equivalent
       False = both known and different (definite bug)
       None  = at least one unknown (cannot verify; not necessarily a bug)
    """
    cell_tt = truth_table_of(cell_type, ref_dir)
    func_tt = truth_table_of(gate_function, ref_dir)
    if cell_tt is None and func_tt is None:
        return (None, f"both unknown: cell={cell_type!r} fn={gate_function!r}")
    if cell_tt is None:
        return (None, f"cell family {family_of(cell_type)!r} not in any loaded library JSON")
    if func_tt is None:
        return (None, f"gate_function {gate_function!r} not in abstract function set")
    if cell_tt == func_tt:
        return (True, "match")
    # String mismatch — could be cosmetic (extra parentheses from Liberty).
    # Verify via brute-force truth-table evaluation over shared input variables.
    import re as _re, itertools as _it
    def _inputs(expr): return sorted(set(_re.findall(r'\b[A-Za-z_]\w*\b', expr)) - {'and','or','not'})
    def _eval(expr, env):
        try: return 1 if (eval(expr, {"__builtins__": {}}, env) & 1) else 0
        except: return None
    cell_expr = next(iter(cell_tt.values()))
    func_expr = next(iter(func_tt.values()))
    all_vars = sorted(set(_inputs(cell_expr)) | set(_inputs(func_expr)))
    if len(all_vars) > 8:
        # Too large for brute force — fall back to string mismatch
        return (False, f"truth table mismatch (string): cell={cell_tt}, claimed={func_tt}")
    mismatch = False
    for combo in _it.product([0, 1], repeat=len(all_vars)):
        env = dict(zip(all_vars, combo))
        cv, fv = _eval(cell_expr, env), _eval(func_expr, env)
        if cv is None or fv is None: break
        if cv != fv: mismatch = True; break
    if not mismatch:
        return (True, "match (logically equivalent despite different notation)")
    return (False, f"truth table mismatch: cell={cell_tt}, claimed={func_tt}")


if __name__ == "__main__":
    # Self-test: verify engine works against whatever library JSONs are loaded
    libs = _load_libraries()
    print(f"Loaded {len(libs)} cell families from cell_libraries/")
    cases = [
        ("AN2D1BWP136P5M156H3P48CPDLVT", "AND2"),
        ("OR4D1BWP136P5M117H3P48CPDLVT", "OR4"),
        ("NR2D1SPG1AMDBWP136P5M156H3P48CPDLVT", "NOR2"),
        ("INR3D1BWP136P5M156H3P48CPDLVT", "NOR3"),
        ("WeirdCell123", "AND2"),
    ]
    for cell, fn in cases:
        m, why = cell_function_matches(cell, fn)
        print(f"  {cell:50s} vs {fn:8s} → {m} ({why})")
