#!/bin/tcsh
# Find equivalent nets using TileBuilderIntFM (Formality ECO)
# Called by agent task execution
# Parameters: refDir, tag, target, netName

set refDir    = $1
set tag       = $2
set target    = $3
set netName   = $4
set tile      = $5
set source_dir = `pwd`
touch $source_dir/data/${tag}_spec

# Strip "refDir:" prefix and any leading colons
set refdir_name = `echo $refDir | sed 's/refDir://' | sed 's/^://g'`

# Strip "target:" prefix
set target_name = `echo $target | sed 's/target://'`

# Strip "netName:" prefix
set net_name  = `echo $netName | sed 's/netName://'`

# Strip tile prefix
set tile_name = `echo $tile | sed 's/:/ /g' | awk '{$1="";print $0}'`

# --- Phase 1: Validate inputs ---

if ("$refdir_name" == "" || "$refdir_name" == " ") then
    echo "ERROR: refDir is empty or invalid" >> $source_dir/data/${tag}_spec
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

if (! -d $refdir_name) then
    echo "ERROR: Directory not found: $refdir_name" >> $source_dir/data/${tag}_spec
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

if (! -f "$refdir_name/revrc.main") then
    echo "ERROR: Not a TileBuilder directory (revrc.main not found)" >> $source_dir/data/${tag}_spec
    echo "Directory: $refdir_name" >> $source_dir/data/${tag}_spec
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

if ("$target_name" == "" || "$target_name" == "target") then
    echo "ERROR: FM target not specified" >> $source_dir/data/${tag}_spec
    echo "Valid targets: FmEqvPreEcoSynthesizeVsPreEcoSynRtl, FmEqvPreEcoPreplaceVsPreEcoSynthesize," >> $source_dir/data/${tag}_spec
    echo "              FmEqvPreEcoRouteVsPreEcoPrePlace, FmEqvEcoSynthesizeVsEcoSynRtl," >> $source_dir/data/${tag}_spec
    echo "              FmEqvEcoPreplaceVsEcoSynthesize, FmEqvEcoRouteVsEcoPrePlace" >> $source_dir/data/${tag}_spec
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

if ("$net_name" == "" || "$net_name" == "netName") then
    echo "ERROR: NetName not specified. Use format: NetName: <module>/<net>" >> $source_dir/data/${tag}_spec
    echo "Example: NetName: umccmd/ARB_BEQ_Cmd1Vld" >> $source_dir/data/${tag}_spec
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

echo "TileBuilder directory: $refdir_name"
echo "FM target:             $target_name"
echo "Net name:              $net_name"

# --- Phase 2: Source LSF environment ---
source $source_dir/script/rtg_oss_feint/lsf_tilebuilder.csh

# --- Phase 3: Check FM target status via TileBuilderShow ---
echo "Checking FM target status via TileBuilderShow..."
set tb_status_log = "/tmp/tb_fm_status_${tag}.log"

cd $refdir_name
TileBuilderTerm -x "TileBuilderShow >& $tb_status_log"
cd $source_dir
sleep 5

set fm_status = "UNKNOWN"
if (-f "$tb_status_log" && -s "$tb_status_log") then
    set fm_status = `grep "$target_name" $tb_status_log | awk '{print $NF}'`
    if ("$fm_status" == "") then
        set fm_status = "NOT_FOUND"
    endif
endif
rm -f $tb_status_log

echo "FM target status: $fm_status"

if ("$fm_status" == "NOTRUN" || "$fm_status" == "RUNNING" || "$fm_status" == "UNKNOWN" || "$fm_status" == "NOT_FOUND") then
    echo "#text#" >> $source_dir/data/${tag}_spec
    echo "ERROR: FM target '$target_name' status is '$fm_status'" >> $source_dir/data/${tag}_spec
    echo "Please ensure the Formality run has completed before running this command." >> $source_dir/data/${tag}_spec
    echo "#text end#" >> $source_dir/data/${tag}_spec
    cd $source_dir
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

echo "FM target is $fm_status — proceeding with find_equivalent_nets"

# --- Phase 4: Generate TCL append script ---
set tcl_script = "/tmp/fm_find_equiv_${tag}.tcl"
set output_rpt = "rpts/${target_name}/find_equivalent_nets.txt"
set result_file = "${refdir_name}/${output_rpt}"

cat > $tcl_script << TCLEOF
# find_equivalent_nets — auto-generated by find_equivalent_nets.csh
# Tag: ${tag}

# Dynamically resolve reference top path via ParamsDB (already sourced by FmInteractive.cmd)
set topModule \$P(TOP_MODULE)
set ref_lib   [string toupper "FMWORK_REF_\${topModule}"]
set ref_top   "\${ref_lib}/\${topModule}"
echo "INFO: ref_top = \$ref_top"

set net_suffix "${tile_name}/${net_name}"
set full_ref_net "r:/\$ref_top/\$net_suffix"
echo "=== find_equivalent_nets for: \$full_ref_net ==="

redirect ${refdir_name}/${output_rpt} {
    echo "=========================================="
    echo "Net: \$full_ref_net"
    echo "=========================================="
    find_equivalent_nets \$full_ref_net
    echo ""
    echo "FIND_EQUIVALENT_NETS_COMPLETE"
}
exit
TCLEOF

echo "Generated TCL script: $tcl_script"

# --- Phase 5: Run TileBuilderIntFM ---
echo "Running TileBuilderIntFM --nogui --append $tcl_script $target_name ..."

# Suppress xterm window by writing to ~/.TileBuilder.general.controls
# TileBuilderIntFM reads this file (not env vars) to control terminal behaviour
set userctl = "$HOME/.TileBuilder.general.controls"
set tb_ctrl_existed = 0
if (-f $userctl) set tb_ctrl_existed = 1
echo "TILEBUILDERINTFM_TERMINAL =" >> $userctl

# Remove stale result file so poll detects only fresh output
rm -f $result_file

cd $refdir_name
TileBuilderTerm -x "TileBuilderIntFM --nogui --append $tcl_script $target_name" &
cd $source_dir

# --- Phase 6: Poll for output file ---
set max_wait = 60
set wait_count = 0

echo "Waiting for output (max ${max_wait} minutes)..."

while ($wait_count < $max_wait)
    sleep 60
    set wait_count = `expr $wait_count + 1`

    if (-f "$result_file") then
        set complete = `grep -c "FIND_EQUIVALENT_NETS_COMPLETE" $result_file`
        if ($complete > 0) then
            echo "Output complete after ${wait_count} minute(s): $result_file"
            break
        endif
    endif

    echo "Waiting... (${wait_count}/${max_wait} minutes elapsed)"
end

set sentinel_found = 0
if (-f "$result_file") set sentinel_found = `grep -c "FIND_EQUIVALENT_NETS_COMPLETE" $result_file`
if (! -f "$result_file" || $sentinel_found == 0) then
    echo "#text#" >> $source_dir/data/${tag}_spec
    echo "ERROR: find_equivalent_nets timed out after ${max_wait} minutes" >> $source_dir/data/${tag}_spec
    echo "Expected output: $result_file" >> $source_dir/data/${tag}_spec
    echo "#text end#" >> $source_dir/data/${tag}_spec
    rm -f $tcl_script
    cd $source_dir
    set run_status = "failed"
    source $source_dir/script/rtg_oss_feint/finishing_task.csh
    exit 1
endif

# --- Phase 7: Write results and finish ---
cat >> $source_dir/data/${tag}_spec << EOF
#table#
Field,Value
FM Target,$target_name
Net,$tile_name/$net_name
Output,$result_file
#table end#
#text#
EOF
grep -v "FIND_EQUIVALENT_NETS_COMPLETE" $result_file >> $source_dir/data/${tag}_spec
echo "#text end#" >> $source_dir/data/${tag}_spec

rm -f $tcl_script

# Restore ~/.TileBuilder.general.controls — remove the suppression line we appended
# If file didn't exist before, remove it entirely; otherwise strip only our added line
if ($tb_ctrl_existed == 0) then
    rm -f $userctl
else
    grep -v "^TILEBUILDERINTFM_TERMINAL" $userctl >! /tmp/tb_ctrl_restore_$$.tmp
    mv /tmp/tb_ctrl_restore_$$.tmp $userctl
endif

cd $source_dir
set run_status = "finished"
source csh/env.csh
source csh/updateTask.csh
